<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MonoAotIncompatible>true</MonoAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="SwiftExtendedLayoutTypes.ilproj" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
    <CMakeProjectReference Include="CMakeLists.txt" />
  </ItemGroup>
</Project>
