// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
//
// Generated by src/tests/Interop/Swift/StressGenerator. Do not edit manually.
// Regenerate with:
//   ./dotnet.sh run --project src/tests/Interop/Swift/StressGenerator -- --seed 20260712 --count 20 --suite args --out <dir> --library-evolution

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Swift;
using Xunit;
using TestLibrary;

[PlatformSpecific(TestPlatforms.AnyApple)]
public unsafe class SwiftEvolutionStress
{
    private const string SwiftLib = "libSwiftEvolutionStress.dylib";

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F0_S0
    {
        public int F0;
        public nint F1;
        public int F2;
        public nuint F3;

        public F0_S0(int f0, nint f1, int f2, nuint f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F0_S1_S0
    {
        public double F0;

        public F0_S1_S0(double f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F0_S1
    {
        public int F0;
        public F0_S1_S0 F1;
        public short F2;
        public sbyte F3;
        public nint F4;

        public F0_S1(int f0, F0_S1_S0 f1, short f2, sbyte f3, nint f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc02a02a12a22a32a42a5Sis5Int64V_s6UInt64Vs5Int32VAA5F0_S0VAjA0O3_S1VtF")]
    private static extern nint SwiftFunc0(long a0, ulong a1, int a2, F0_S0 a3, long a4, F0_S1 a5);

    [Fact]
    public static void TestSwiftFunc0()
    {
        Console.Write("Running SwiftFunc0: ");
        long result = SwiftFunc0(4234820095401308513, 7114490079459766822, -111580148, new F0_S0(-511736360, unchecked((nint)767551968211148277), -294371741, unchecked((nuint)7860037210568015119)), -7902107703978802179, new F0_S1(-1728237372, new F0_S1_S0(449926154011145), 3784, 113, unchecked((nint)(-1690235160688213166))));
        Assert.Equal(7628462936565498463, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F1_S0
    {
        public uint F0;
        public short F1;
        public byte F2;
        public sbyte F3;
        public int F4;
        public double F5;

        public F1_S0(uint f0, short f1, byte f2, sbyte f3, int f4, double f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 4)]
    struct F1_S1
    {
        public int F0;

        public F1_S1(int f0)
        {
            F0 = f0;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc12a02a12a22a32a4SiAA5F1_S0V_Sis5UInt8VSiAA0K3_S1VtF")]
    private static extern nint SwiftFunc1(F1_S0 a0, nint a1, byte a2, nint a3, F1_S1 a4);

    [Fact]
    public static void TestSwiftFunc1()
    {
        Console.Write("Running SwiftFunc1: ");
        long result = SwiftFunc1(new F1_S0(2210345152, -98, 216, 81, -2145432701, 113672511505076), unchecked((nint)1888206631016713839), 70, unchecked((nint)6043190669783092979), new F1_S1(195313711));
        Assert.Equal(-8234220438853667403, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F2_S0
    {
        public byte F0;
        public nuint F1;
        public uint F2;
        public int F3;
        public nint F4;

        public F2_S0(byte f0, nuint f1, uint f2, int f3, nint f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc22a02a12a22a3SiSd_s5UInt8VAA5F2_S0Vs5Int64VtF")]
    private static extern nint SwiftFunc2(double a0, byte a1, F2_S0 a2, long a3);

    [Fact]
    public static void TestSwiftFunc2()
    {
        Console.Write("Running SwiftFunc2: ");
        long result = SwiftFunc2(755356302879180, 170, new F2_S0(250, unchecked((nuint)12148949939584325539), 2947131117, 127698678, unchecked((nint)(-4262280244044533632))), -6874859876332077067);
        Assert.Equal(2349866436972255113, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 20)]
    struct F3_S0_S0
    {
        public short F0;
        public ulong F1;
        public float F2;

        public F3_S0_S0(short f0, ulong f1, float f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F3_S0
    {
        public ushort F0;
        public uint F1;
        public F3_S0_S0 F2;
        public float F3;

        public F3_S0(ushort f0, uint f1, F3_S0_S0 f2, float f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc32a0SiAA5F3_S0V_tF")]
    private static extern nint SwiftFunc3(F3_S0 a0);

    [Fact]
    public static void TestSwiftFunc3()
    {
        Console.Write("Running SwiftFunc3: ");
        long result = SwiftFunc3(new F3_S0(40280, 3083984143, new F3_S0_S0(6892, 17955795952244776287, 16613065), 1645273));
        Assert.Equal(-2977071427480664213, result);
        Console.WriteLine("OK");
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc42a02a12a22a32a42a5SiSd_Sus6UInt64VSds5Int16VSftF")]
    private static extern nint SwiftFunc4(double a0, nuint a1, ulong a2, double a3, short a4, float a5);

    [Fact]
    public static void TestSwiftFunc4()
    {
        Console.Write("Running SwiftFunc4: ");
        long result = SwiftFunc4(934512200509152, unchecked((nuint)11351218287938333807), 7370259827589810320, 209794088195352, 4991, 13510954);
        Assert.Equal(-290382802975921495, result);
        Console.WriteLine("OK");
    }

    [InlineArray(4)]
    struct F5_S0
    {
        private float _element0;
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F5_S1
    {
        public long F0;

        public F5_S1(long f0)
        {
            F0 = f0;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc52a02a12a22a32a42a52a6Sis4Int8V_s6UInt32VAKs6UInt16VAA5F5_S0VAA0P3_S1Vs6UInt64VtF")]
    private static extern nint SwiftFunc5(sbyte a0, uint a1, sbyte a2, ushort a3, F5_S0 a4, F5_S1 a5, ulong a6);

    [Fact]
    public static void TestSwiftFunc5()
    {
        Console.Write("Running SwiftFunc5: ");
        F5_S0 a4 = default;
        float* ptr_a4 = (float*)&a4;
        ptr_a4[0] = (float)10269886;
        ptr_a4[1] = (float)5821273;
        ptr_a4[2] = (float)7626685;
        ptr_a4[3] = (float)10405923;
        long result = SwiftFunc5(84, 734118095, 22, 5978, a4, new F5_S1(6934722774920326055), 15401679344790936674);
        Assert.Equal(-2789192582231990868, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 48)]
    struct F6_S0
    {
        public byte F0;
        public nint F1;
        public uint F2;
        public double F3;
        public short F4;
        public double F5;

        public F6_S0(byte f0, nint f1, uint f2, double f3, short f4, double f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F6_S1_S0_S0
    {
        public ulong F0;

        public F6_S1_S0_S0(ulong f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F6_S1_S0
    {
        public float F0;
        public F6_S1_S0_S0 F1;
        public ulong F2;

        public F6_S1_S0(float f0, F6_S1_S0_S0 f1, ulong f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 68)]
    struct F6_S1
    {
        public ulong F0;
        public ulong F1;
        public F6_S1_S0 F2;
        public nuint F3;
        public uint F4;
        public long F5;
        public uint F6;

        public F6_S1(ulong f0, ulong f1, F6_S1_S0 f2, nuint f3, uint f4, long f5, uint f6)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc62a02a12a22a3SiAA5F6_S0V_s5Int32VAA0J3_S1Vs6UInt64VtF")]
    private static extern nint SwiftFunc6(F6_S0 a0, int a1, F6_S1 a2, ulong a3);

    [Fact]
    public static void TestSwiftFunc6()
    {
        Console.Write("Running SwiftFunc6: ");
        long result = SwiftFunc6(new F6_S0(140, unchecked((nint)6902063804009597545), 1409675622, 27738730753164, 31523, 144748116790482), -1479314120, new F6_S1(14693012199546982376, 9537435413972136564, new F6_S1_S0(3591412, new F6_S1_S0_S0(1452644469926763974), 17306187098189134240), unchecked((nuint)5246898188083355281), 3362037538, -1896763159536371773, 1757134693), 4108424734600824817);
        Assert.Equal(549372169616269129, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 4)]
    struct F7_S0_S0_S0
    {
        public int F0;

        public F7_S0_S0_S0(int f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 12)]
    struct F7_S0_S0
    {
        public byte F0;
        public F7_S0_S0_S0 F1;
        public sbyte F2;
        public short F3;

        public F7_S0_S0(byte f0, F7_S0_S0_S0 f1, sbyte f2, short f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 56)]
    struct F7_S0
    {
        public F7_S0_S0 F0;
        public nint F1;
        public int F2;
        public ushort F3;
        public int F4;
        public uint F5;
        public long F6;
        public nint F7;

        public F7_S0(F7_S0_S0 f0, nint f1, int f2, ushort f3, int f4, uint f5, long f6, nint f7)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
            F7 = f7;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 28)]
    struct F7_S1
    {
        public byte F0;
        public short F1;
        public float F2;
        public ulong F3;
        public ulong F4;
        public float F5;

        public F7_S1(byte f0, short f1, float f2, ulong f3, ulong f4, float f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 13)]
    struct F7_S2
    {
        public double F0;
        public ushort F1;
        public ushort F2;
        public sbyte F3;

        public F7_S2(double f0, ushort f1, ushort f2, sbyte f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc72a02a12a22a32a42a5Sis5Int16V_s5Int32Vs5Int64VAA5F7_S0VAA0O3_S1VAA0O3_S2VtF")]
    private static extern nint SwiftFunc7(short a0, int a1, long a2, F7_S0 a3, F7_S1 a4, F7_S2 a5);

    [Fact]
    public static void TestSwiftFunc7()
    {
        Console.Write("Running SwiftFunc7: ");
        long result = SwiftFunc7(21106, 681937547, 2353486216648261256, new F7_S0(new F7_S0_S0(214, new F7_S0_S0_S0(307281532), 119, -17942), unchecked((nint)37294327001239368), 2138248181, 57215, -1283607768, 1270112868, 7292208031084066089, unchecked((nint)(-3597637588735190890))), new F7_S1(162, 17065, 1790638, 5007481666254614307, 5709848595969242511, 9776944), new F7_S2(312352847410367, 50605, 4541, 94));
        Assert.Equal(-2723535676227443490, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F8_S0
    {
        public nint F0;
        public long F1;
        public int F2;
        public ushort F3;
        public ulong F4;

        public F8_S0(nint f0, long f1, int f2, ushort f3, ulong f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc82a02a1SiAA5F8_S0V_s5Int32VtF")]
    private static extern nint SwiftFunc8(F8_S0 a0, int a1);

    [Fact]
    public static void TestSwiftFunc8()
    {
        Console.Write("Running SwiftFunc8: ");
        long result = SwiftFunc8(new F8_S0(unchecked((nint)505809536608248847), -1814637022437036906, 463821875, 17940, 16634969305317011418), -1319265202);
        Assert.Equal(-3936918152932248234, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F9_S0_S0_S0
    {
        public nuint F0;

        public F9_S0_S0_S0(nuint f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 12)]
    struct F9_S0_S0
    {
        public F9_S0_S0_S0 F0;
        public uint F1;

        public F9_S0_S0(F9_S0_S0_S0 f0, uint f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 34)]
    struct F9_S0
    {
        public ulong F0;
        public F9_S0_S0 F1;
        public byte F2;
        public ulong F3;
        public ushort F4;

        public F9_S0(ulong f0, F9_S0_S0 f1, byte f2, ulong f3, ushort f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 12)]
    struct F9_S1
    {
        public uint F0;
        public int F1;
        public float F2;

        public F9_S1(uint f0, int f1, float f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress10swiftFunc92a02a12a22a32a42a52a62a72a82a9Sis5UInt8V_Sus6UInt64VAPs5Int32VSdAA5F9_S0VANSuAA0S3_S1VtF")]
    private static extern nint SwiftFunc9(byte a0, nuint a1, ulong a2, ulong a3, int a4, double a5, F9_S0 a6, byte a7, nuint a8, F9_S1 a9);

    [Fact]
    public static void TestSwiftFunc9()
    {
        Console.Write("Running SwiftFunc9: ");
        long result = SwiftFunc9(68, unchecked((nuint)11540444339326051231), 15522965533099501222, 3427316880117599535, 1988206073, 598832730270616, new F9_S0(11196341210797601783, new F9_S0_S0(new F9_S0_S0_S0(unchecked((nuint)4876373375532448142)), 3468906582), 168, 4185031592641606830, 2951), 96, unchecked((nuint)3448110204648319221), new F9_S1(1036149046, 555478699, 4214099));
        Assert.Equal(3628362977674014384, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F10_S0
    {
        public float F0;
        public float F1;
        public float F2;
        public float F3;
        public float F4;
        public float F5;

        public F10_S0(float f0, float f1, float f2, float f3, float f4, float f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 26)]
    struct F10_S1
    {
        public nint F0;
        public sbyte F1;
        public nuint F2;
        public short F3;

        public F10_S1(nint f0, sbyte f1, nuint f2, short f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 16)]
    struct F10_S2
    {
        public sbyte F0;
        public nint F1;

        public F10_S2(sbyte f0, nint f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 4)]
    struct F10_S3
    {
        public float F0;

        public F10_S3(float f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 6)]
    struct F10_S4_S0
    {
        public sbyte F0;
        public ushort F1;
        public short F2;

        public F10_S4_S0(sbyte f0, ushort f1, short f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 44)]
    struct F10_S4
    {
        public ushort F0;
        public byte F1;
        public uint F2;
        public long F3;
        public F10_S4_S0 F4;
        public long F5;
        public ulong F6;
        public uint F7;

        public F10_S4(ushort f0, byte f1, uint f2, long f3, F10_S4_S0 f4, long f5, ulong f6, uint f7)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
            F7 = f7;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc102a02a12a22a32a42a52a62a7S2i_AA6F10_S0Vs5Int16VAA0N3_S1VAA0N3_S2Vs6UInt64VAA0N3_S3VAA0N3_S4VtF")]
    private static extern nint SwiftFunc10(nint a0, F10_S0 a1, short a2, F10_S1 a3, F10_S2 a4, ulong a5, F10_S3 a6, F10_S4 a7);

    [Fact]
    public static void TestSwiftFunc10()
    {
        Console.Write("Running SwiftFunc10: ");
        long result = SwiftFunc10(unchecked((nint)(-8011814620787933658)), new F10_S0(13665002, 15713481, 4561002, 1186209, 5006805, 4472313), -1504, new F10_S1(unchecked((nint)(-2280495748378406993)), 32, unchecked((nuint)56546986230599513), 24983), new F10_S2(60, unchecked((nint)(-210746463372892259))), 11025047624050576273, new F10_S3(14073212), new F10_S4(37718, 17, 2353579343, -4584474764298516300, new F10_S4_S0(126, 48241, 10133), -7099232949925475415, 10794862780653142354, 2475700846));
        Assert.Equal(4146846725074184987, result);
        Console.WriteLine("OK");
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc112a02a12a22a32a42a5Sis5Int16V_S2ds5UInt8Vs5Int32Vs4Int8VtF")]
    private static extern nint SwiftFunc11(short a0, double a1, double a2, byte a3, int a4, sbyte a5);

    [Fact]
    public static void TestSwiftFunc11()
    {
        Console.Write("Running SwiftFunc11: ");
        long result = SwiftFunc11(-27433, 1043221590865992, 723841623088776, 92, -113653741, -125);
        Assert.Equal(8574221706310573041, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F12_S0_S0
    {
        public long F0;
        public float F1;
        public short F2;
        public nuint F3;

        public F12_S0_S0(long f0, float f1, short f2, nuint f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F12_S0
    {
        public F12_S0_S0 F0;
        public ulong F1;

        public F12_S0(F12_S0_S0 f0, ulong f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 1)]
    struct F12_S1
    {
        public byte F0;

        public F12_S1(byte f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 48)]
    struct F12_S2
    {
        public byte F0;
        public long F1;
        public short F2;
        public ulong F3;
        public byte F4;
        public nint F5;

        public F12_S2(byte f0, long f1, short f2, ulong f3, byte f4, nint f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc122a02a12a2SiAA6F12_S0V_AA0I3_S1VAA0I3_S2VtF")]
    private static extern nint SwiftFunc12(F12_S0 a0, F12_S1 a1, F12_S2 a2);

    [Fact]
    public static void TestSwiftFunc12()
    {
        Console.Write("Running SwiftFunc12: ");
        long result = SwiftFunc12(new F12_S0(new F12_S0_S0(-701130056746808676, 9783876, -24892, unchecked((nuint)8857891717606660621)), 1684310831806161946), new F12_S1(39), new F12_S2(218, 8045507707361170172, -12399, 16729795567450810926, 27, unchecked((nint)4221505797969766052)));
        Assert.Equal(-3733788692963993593, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 28)]
    struct F13_S0
    {
        public sbyte F0;
        public double F1;
        public float F2;
        public int F3;
        public sbyte F4;
        public ushort F5;

        public F13_S0(sbyte f0, double f1, float f2, int f3, sbyte f4, ushort f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 2)]
    struct F13_S1_S0
    {
        public sbyte F0;
        public byte F1;

        public F13_S1_S0(sbyte f0, byte f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 26)]
    struct F13_S1_S1
    {
        public nint F0;
        public short F1;
        public long F2;
        public short F3;

        public F13_S1_S1(nint f0, short f1, long f2, short f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F13_S1_S2
    {
        public long F0;

        public F13_S1_S2(long f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 57)]
    struct F13_S1
    {
        public uint F0;
        public F13_S1_S0 F1;
        public ushort F2;
        public int F3;
        public short F4;
        public F13_S1_S1 F5;
        public F13_S1_S2 F6;
        public byte F7;

        public F13_S1(uint f0, F13_S1_S0 f1, ushort f2, int f3, short f4, F13_S1_S1 f5, F13_S1_S2 f6, byte f7)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
            F7 = f7;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 20)]
    struct F13_S2
    {
        public byte F0;
        public nint F1;
        public uint F2;

        public F13_S2(byte f0, nint f1, uint f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F13_S3_S0
    {
        public float F0;
        public uint F1;
        public int F2;
        public nint F3;

        public F13_S3_S0(float f0, uint f1, int f2, nint f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F13_S3
    {
        public ushort F0;
        public F13_S3_S0 F1;

        public F13_S3(ushort f0, F13_S3_S0 f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc132a02a12a22a32a4SiAA6F13_S0V_AA0K3_S1VAA0K3_S2Vs4Int8VAA0K3_S3VtF")]
    private static extern nint SwiftFunc13(F13_S0 a0, F13_S1 a1, F13_S2 a2, sbyte a3, F13_S3 a4);

    [Fact]
    public static void TestSwiftFunc13()
    {
        Console.Write("Running SwiftFunc13: ");
        long result = SwiftFunc13(new F13_S0(-43, 578547069840118, 14203174, 2128404967, -62, 56944), new F13_S1(1539867926, new F13_S1_S0(-128, 73), 17501, 1733443370, -13768, new F13_S1_S1(unchecked((nint)(-3827441095463756088)), 1222, -4341409612774489085, -15569), new F13_S1_S2(-8077535906245766818), 239), new F13_S2(148, unchecked((nint)(-1647934719597327267)), 1357107450), 31, new F13_S3(57827, new F13_S3_S0(2941951, 2662010832, -318688507, unchecked((nint)(-3440249721379796612)))));
        Assert.Equal(-133284017677309087, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F14_S0_S0
    {
        public ulong F0;

        public F14_S0_S0(ulong f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 36)]
    struct F14_S0
    {
        public F14_S0_S0 F0;
        public float F1;
        public int F2;
        public sbyte F3;
        public ushort F4;
        public nint F5;
        public uint F6;

        public F14_S0(F14_S0_S0 f0, float f1, int f2, sbyte f3, ushort f4, nint f5, uint f6)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 14)]
    struct F14_S1
    {
        public float F0;
        public byte F1;
        public uint F2;
        public short F3;

        public F14_S1(float f0, byte f1, uint f2, short f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 5)]
    struct F14_S2_S0_S0
    {
        public short F0;
        public sbyte F1;
        public byte F2;
        public byte F3;

        public F14_S2_S0_S0(short f0, sbyte f1, byte f2, byte f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 17)]
    struct F14_S2_S0
    {
        public F14_S2_S0_S0 F0;
        public long F1;
        public sbyte F2;

        public F14_S2_S0(F14_S2_S0_S0 f0, long f1, sbyte f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 30)]
    struct F14_S2
    {
        public int F0;
        public F14_S2_S0 F1;
        public short F2;
        public ushort F3;

        public F14_S2(int f0, F14_S2_S0 f1, short f2, ushort f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc142a02a12a22a32a42a52a6SiAA6F14_S0V_Sds5Int16Vs4Int8VAA0M3_S1VAA0M3_S2Vs5Int64VtF")]
    private static extern nint SwiftFunc14(F14_S0 a0, double a1, short a2, sbyte a3, F14_S1 a4, F14_S2 a5, long a6);

    [Fact]
    public static void TestSwiftFunc14()
    {
        Console.Write("Running SwiftFunc14: ");
        long result = SwiftFunc14(new F14_S0(new F14_S0_S0(14941817675562648132), 432415, 1943303596, -12, 10389, unchecked((nint)8739753642143428077), 2857742923), 1021015103290308, -9381, 107, new F14_S1(7009994, 142, 2763318421, 25071), new F14_S2(-1620256806, new F14_S2_S0(new F14_S2_S0_S0(32374, -24, 254, 247), 994242886959389724, 41), -10402, 6621), -8478387874313790129);
        Assert.Equal(-1885081218101048250, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 46)]
    struct F15_S0
    {
        public float F0;
        public sbyte F1;
        public double F2;
        public int F3;
        public double F4;
        public long F5;
        public int F6;
        public short F7;

        public F15_S0(float f0, sbyte f1, double f2, int f3, double f4, long f5, int f6, short f7)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
            F7 = f7;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc152a0SiAA6F15_S0V_tF")]
    private static extern nint SwiftFunc15(F15_S0 a0);

    [Fact]
    public static void TestSwiftFunc15()
    {
        Console.Write("Running SwiftFunc15: ");
        long result = SwiftFunc15(new F15_S0(9811798, 91, 138464544666240, -1205836960, 50233254715095, 200670988324373008, -1363383938, -7182));
        Assert.Equal(5489423464279263899, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 4)]
    struct F16_S0
    {
        public int F0;

        public F16_S0(int f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 4)]
    struct F16_S1
    {
        public uint F0;

        public F16_S1(uint f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 48)]
    struct F16_S2
    {
        public sbyte F0;
        public byte F1;
        public long F2;
        public nint F3;
        public uint F4;
        public long F5;
        public long F6;

        public F16_S2(sbyte f0, byte f1, long f2, nint f3, uint f4, long f5, long f6)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F16_S3
    {
        public double F0;
        public double F1;
        public double F2;
        public double F3;

        public F16_S3(double f0, double f1, double f2, double f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 18)]
    struct F16_S4_S0_S0
    {
        public ushort F0;
        public short F1;
        public nuint F2;
        public short F3;

        public F16_S4_S0_S0(ushort f0, short f1, nuint f2, short f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 42)]
    struct F16_S4_S0
    {
        public long F0;
        public sbyte F1;
        public ulong F2;
        public F16_S4_S0_S0 F3;

        public F16_S4_S0(long f0, sbyte f1, ulong f2, F16_S4_S0_S0 f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 24)]
    struct F16_S4_S1
    {
        public short F0;
        public nuint F1;
        public nint F2;

        public F16_S4_S1(short f0, nuint f1, nint f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 89)]
    struct F16_S4
    {
        public float F0;
        public F16_S4_S0 F1;
        public ushort F2;
        public short F3;
        public F16_S4_S1 F4;
        public double F5;
        public byte F6;

        public F16_S4(float f0, F16_S4_S0 f1, ushort f2, short f3, F16_S4_S1 f4, double f5, byte f6)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc162a02a12a22a32a42a52a62a7SiAA6F16_S0V_Sus6UInt64VAA0N3_S1VAA0N3_S2VAA0N3_S3Vs5Int32VAA0N3_S4VtF")]
    private static extern nint SwiftFunc16(F16_S0 a0, nuint a1, ulong a2, F16_S1 a3, F16_S2 a4, F16_S3 a5, int a6, F16_S4 a7);

    [Fact]
    public static void TestSwiftFunc16()
    {
        Console.Write("Running SwiftFunc16: ");
        long result = SwiftFunc16(new F16_S0(568513400), unchecked((nuint)1994813273280979914), 12344982273512767791, new F16_S1(3408859166), new F16_S2(-82, 154, 4351637491170309141, unchecked((nint)(-6687825362411697471)), 2610950887, -2100233853261047599, -8792852433495407756), new F16_S3(903074654936594, 571036645034131, 229267969854692, 40585477395812), -1488183288, new F16_S4(10965410, new F16_S4_S0(6981353387983981186, -75, 12941926886500437063, new F16_S4_S0_S0(33867, 64, unchecked((nuint)17743379518276985040), -3415)), 58831, -5344, new F16_S4_S1(-8456, unchecked((nuint)13875781626487706009), unchecked((nint)2790295133692260464)), 727114706234168, 209));
        Assert.Equal(-7901630203269747891, result);
        Console.WriteLine("OK");
    }

    [InlineArray(16)]
    struct F17_S0
    {
        private short _element0;
    }

    [StructLayout(LayoutKind.Sequential, Size = 41)]
    struct F17_S1
    {
        public sbyte F0;
        public double F1;
        public nuint F2;
        public byte F3;
        public long F4;
        public sbyte F5;

        public F17_S1(sbyte f0, double f1, nuint f2, byte f3, long f4, sbyte f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 16)]
    struct F17_S2_S0
    {
        public short F0;
        public int F1;
        public int F2;
        public uint F3;

        public F17_S2_S0(short f0, int f1, int f2, uint f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 16)]
    struct F17_S2
    {
        public F17_S2_S0 F0;

        public F17_S2(F17_S2_S0 f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F17_S3_S0
    {
        public ulong F0;

        public F17_S3_S0(ulong f0)
        {
            F0 = f0;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 32)]
    struct F17_S3
    {
        public double F0;
        public byte F1;
        public long F2;
        public F17_S3_S0 F3;

        public F17_S3(double f0, byte f1, long f2, F17_S3_S0 f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc172a02a12a22a32a42a52a6Sis4Int8V_AA6F17_S0VAA0N3_S1Vs5UInt8VAA0N3_S2VAA0N3_S3Vs5Int64VtF")]
    private static extern nint SwiftFunc17(sbyte a0, F17_S0 a1, F17_S1 a2, byte a3, F17_S2 a4, F17_S3 a5, long a6);

    [Fact]
    public static void TestSwiftFunc17()
    {
        Console.Write("Running SwiftFunc17: ");
        F17_S0 a1 = default;
        short* ptr_a1 = (short*)&a1;
        ptr_a1[0] = (short)17908;
        ptr_a1[1] = (short)2935;
        ptr_a1[2] = (short)11299;
        ptr_a1[3] = (short)-22994;
        ptr_a1[4] = (short)29745;
        ptr_a1[5] = (short)22497;
        ptr_a1[6] = (short)-6161;
        ptr_a1[7] = (short)21065;
        ptr_a1[8] = (short)28564;
        ptr_a1[9] = (short)24206;
        ptr_a1[10] = (short)24766;
        ptr_a1[11] = (short)15825;
        ptr_a1[12] = (short)22021;
        ptr_a1[13] = (short)-21879;
        ptr_a1[14] = (short)-25300;
        ptr_a1[15] = (short)-23929;
        long result = SwiftFunc17(24, a1, new F17_S1(-120, 945474097312498, unchecked((nuint)9213303486925704741), 147, 459042860626642194, -20), 101, new F17_S2(new F17_S2_S0(-27792, -1329403116, 1376880433, 1265403676)), new F17_S3(321403886557637, 8, 2658787621523812262, new F17_S3_S0(14050205443701586788)), 6970185528588263762);
        Assert.Equal(7888550664837390309, result);
        Console.WriteLine("OK");
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc182a02a1SiSf_s6UInt16VtF")]
    private static extern nint SwiftFunc18(float a0, ushort a1);

    [Fact]
    public static void TestSwiftFunc18()
    {
        Console.Write("Running SwiftFunc18: ");
        long result = SwiftFunc18(11623283, 64122);
        Assert.Equal(5186644451070439471, result);
        Console.WriteLine("OK");
    }

    [StructLayout(LayoutKind.Sequential, Size = 8)]
    struct F19_S0
    {
        public float F0;
        public float F1;

        public F19_S0(float f0, float f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 7)]
    struct F19_S1
    {
        public uint F0;
        public sbyte F1;
        public byte F2;
        public byte F3;

        public F19_S1(uint f0, sbyte f1, byte f2, byte f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Size = 20)]
    struct F19_S2
    {
        public double F0;
        public sbyte F1;
        public float F2;
        public short F3;
        public short F4;

        public F19_S2(double f0, sbyte f1, float f2, short f3, short f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]
    [DllImport(SwiftLib, EntryPoint = "$s20SwiftEvolutionStress11swiftFunc192a02a12a22a32a42a52a6SiAA6F19_S0V_s6UInt64VSdAA0M3_S1Vs5UInt8VAqA0M3_S2VtF")]
    private static extern nint SwiftFunc19(F19_S0 a0, ulong a1, double a2, F19_S1 a3, byte a4, byte a5, F19_S2 a6);

    [Fact]
    public static void TestSwiftFunc19()
    {
        Console.Write("Running SwiftFunc19: ");
        long result = SwiftFunc19(new F19_S0(9283441, 8559649), 2527854548896284998, 937654414094244, new F19_S1(2522394981, -104, 218, 76), 137, 234, new F19_S2(921062259224973, -80, 14394366, 14746, -22445));
        Assert.Equal(2405766441164731416, result);
        Console.WriteLine("OK");
    }
}
