// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
//
// Generated by src/tests/Interop/Swift/StressGenerator. Do not edit manually.
// Regenerate with:
//   ./dotnet.sh run --project src/tests/Interop/Swift/StressGenerator -- --seed 20260712 --count 20 --suite args --out <dir> --library-evolution

import Foundation

struct HasherFNV1a {

    private var hash: UInt = 14_695_981_039_346_656_037
    private let prime: UInt = 1_099_511_628_211

    mutating func combine<T>(_ val: T) {
        for byte in withUnsafeBytes(of: val, Array.init) {
            hash ^= UInt(byte)
            hash = hash &* prime
        }
    }

    func finalize() -> Int {
        Int(truncatingIfNeeded: hash)
    }
}

@frozen
public struct F0_S0
{
    public let f0 : Int32;
    public let f1 : Int;
    public let f2 : Int32;
    public let f3 : UInt;
}

@frozen
public struct F0_S1_S0
{
    public let f0 : Double;
}

@frozen
public struct F0_S1
{
    public let f0 : Int32;
    public let f1 : F0_S1_S0;
    public let f2 : Int16;
    public let f3 : Int8;
    public let f4 : Int;
}

public func swiftFunc0(a0: Int64, a1: UInt64, a2: Int32, a3: F0_S0, a4: Int64, a5: F0_S1) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3.f0);
    hasher.combine(a3.f1);
    hasher.combine(a3.f2);
    hasher.combine(a3.f3);
    hasher.combine(a4);
    hasher.combine(a5.f0);
    hasher.combine(a5.f1.f0);
    hasher.combine(a5.f2);
    hasher.combine(a5.f3);
    hasher.combine(a5.f4);
    return hasher.finalize()
}

@frozen
public struct F1_S0
{
    public let f0 : UInt32;
    public let f1 : Int16;
    public let f2 : UInt8;
    public let f3 : Int8;
    public let f4 : Int32;
    public let f5 : Double;
}

@frozen
public struct F1_S1
{
    public let f0 : Int32;
}

public func swiftFunc1(a0: F1_S0, a1: Int, a2: UInt8, a3: Int, a4: F1_S1) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a0.f5);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4.f0);
    return hasher.finalize()
}

@frozen
public struct F2_S0
{
    public let f0 : UInt8;
    public let f1 : UInt;
    public let f2 : UInt32;
    public let f3 : Int32;
    public let f4 : Int;
}

public func swiftFunc2(a0: Double, a1: UInt8, a2: F2_S0, a3: Int64) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2.f0);
    hasher.combine(a2.f1);
    hasher.combine(a2.f2);
    hasher.combine(a2.f3);
    hasher.combine(a2.f4);
    hasher.combine(a3);
    return hasher.finalize()
}

@frozen
public struct F3_S0_S0
{
    public let f0 : Int16;
    public let f1 : UInt64;
    public let f2 : Float;
}

@frozen
public struct F3_S0
{
    public let f0 : UInt16;
    public let f1 : UInt32;
    public let f2 : F3_S0_S0;
    public let f3 : Float;
}

public func swiftFunc3(a0: F3_S0) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2.f0);
    hasher.combine(a0.f2.f1);
    hasher.combine(a0.f2.f2);
    hasher.combine(a0.f3);
    return hasher.finalize()
}

public func swiftFunc4(a0: Double, a1: UInt, a2: UInt64, a3: Double, a4: Int16, a5: Float) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4);
    hasher.combine(a5);
    return hasher.finalize()
}

@frozen
public struct F5_S0
{
    public var elements: (Float, Float, Float, Float)
}

@frozen
public struct F5_S1
{
    public let f0 : Int64;
}

public func swiftFunc5(a0: Int8, a1: UInt32, a2: Int8, a3: UInt16, a4: F5_S0, a5: F5_S1, a6: UInt64) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4.elements.0);
    hasher.combine(a4.elements.1);
    hasher.combine(a4.elements.2);
    hasher.combine(a4.elements.3);
    hasher.combine(a5.f0);
    hasher.combine(a6);
    return hasher.finalize()
}

@frozen
public struct F6_S0
{
    public let f0 : UInt8;
    public let f1 : Int;
    public let f2 : UInt32;
    public let f3 : Double;
    public let f4 : Int16;
    public let f5 : Double;
}

@frozen
public struct F6_S1_S0_S0
{
    public let f0 : UInt64;
}

@frozen
public struct F6_S1_S0
{
    public let f0 : Float;
    public let f1 : F6_S1_S0_S0;
    public let f2 : UInt64;
}

@frozen
public struct F6_S1
{
    public let f0 : UInt64;
    public let f1 : UInt64;
    public let f2 : F6_S1_S0;
    public let f3 : UInt;
    public let f4 : UInt32;
    public let f5 : Int64;
    public let f6 : UInt32;
}

public func swiftFunc6(a0: F6_S0, a1: Int32, a2: F6_S1, a3: UInt64) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a0.f5);
    hasher.combine(a1);
    hasher.combine(a2.f0);
    hasher.combine(a2.f1);
    hasher.combine(a2.f2.f0);
    hasher.combine(a2.f2.f1.f0);
    hasher.combine(a2.f2.f2);
    hasher.combine(a2.f3);
    hasher.combine(a2.f4);
    hasher.combine(a2.f5);
    hasher.combine(a2.f6);
    hasher.combine(a3);
    return hasher.finalize()
}

@frozen
public struct F7_S0_S0_S0
{
    public let f0 : Int32;
}

@frozen
public struct F7_S0_S0
{
    public let f0 : UInt8;
    public let f1 : F7_S0_S0_S0;
    public let f2 : Int8;
    public let f3 : Int16;
}

@frozen
public struct F7_S0
{
    public let f0 : F7_S0_S0;
    public let f1 : Int;
    public let f2 : Int32;
    public let f3 : UInt16;
    public let f4 : Int32;
    public let f5 : UInt32;
    public let f6 : Int64;
    public let f7 : Int;
}

@frozen
public struct F7_S1
{
    public let f0 : UInt8;
    public let f1 : Int16;
    public let f2 : Float;
    public let f3 : UInt64;
    public let f4 : UInt64;
    public let f5 : Float;
}

@frozen
public struct F7_S2
{
    public let f0 : Double;
    public let f1 : UInt16;
    public let f2 : UInt16;
    public let f3 : Int8;
}

public func swiftFunc7(a0: Int16, a1: Int32, a2: Int64, a3: F7_S0, a4: F7_S1, a5: F7_S2) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3.f0.f0);
    hasher.combine(a3.f0.f1.f0);
    hasher.combine(a3.f0.f2);
    hasher.combine(a3.f0.f3);
    hasher.combine(a3.f1);
    hasher.combine(a3.f2);
    hasher.combine(a3.f3);
    hasher.combine(a3.f4);
    hasher.combine(a3.f5);
    hasher.combine(a3.f6);
    hasher.combine(a3.f7);
    hasher.combine(a4.f0);
    hasher.combine(a4.f1);
    hasher.combine(a4.f2);
    hasher.combine(a4.f3);
    hasher.combine(a4.f4);
    hasher.combine(a4.f5);
    hasher.combine(a5.f0);
    hasher.combine(a5.f1);
    hasher.combine(a5.f2);
    hasher.combine(a5.f3);
    return hasher.finalize()
}

@frozen
public struct F8_S0
{
    public let f0 : Int;
    public let f1 : Int64;
    public let f2 : Int32;
    public let f3 : UInt16;
    public let f4 : UInt64;
}

public func swiftFunc8(a0: F8_S0, a1: Int32) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a1);
    return hasher.finalize()
}

@frozen
public struct F9_S0_S0_S0
{
    public let f0 : UInt;
}

@frozen
public struct F9_S0_S0
{
    public let f0 : F9_S0_S0_S0;
    public let f1 : UInt32;
}

@frozen
public struct F9_S0
{
    public let f0 : UInt64;
    public let f1 : F9_S0_S0;
    public let f2 : UInt8;
    public let f3 : UInt64;
    public let f4 : UInt16;
}

@frozen
public struct F9_S1
{
    public let f0 : UInt32;
    public let f1 : Int32;
    public let f2 : Float;
}

public func swiftFunc9(a0: UInt8, a1: UInt, a2: UInt64, a3: UInt64, a4: Int32, a5: Double, a6: F9_S0, a7: UInt8, a8: UInt, a9: F9_S1) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4);
    hasher.combine(a5);
    hasher.combine(a6.f0);
    hasher.combine(a6.f1.f0.f0);
    hasher.combine(a6.f1.f1);
    hasher.combine(a6.f2);
    hasher.combine(a6.f3);
    hasher.combine(a6.f4);
    hasher.combine(a7);
    hasher.combine(a8);
    hasher.combine(a9.f0);
    hasher.combine(a9.f1);
    hasher.combine(a9.f2);
    return hasher.finalize()
}

@frozen
public struct F10_S0
{
    public let f0 : Float;
    public let f1 : Float;
    public let f2 : Float;
    public let f3 : Float;
    public let f4 : Float;
    public let f5 : Float;
}

@frozen
public struct F10_S1
{
    public let f0 : Int;
    public let f1 : Int8;
    public let f2 : UInt;
    public let f3 : Int16;
}

@frozen
public struct F10_S2
{
    public let f0 : Int8;
    public let f1 : Int;
}

@frozen
public struct F10_S3
{
    public let f0 : Float;
}

@frozen
public struct F10_S4_S0
{
    public let f0 : Int8;
    public let f1 : UInt16;
    public let f2 : Int16;
}

@frozen
public struct F10_S4
{
    public let f0 : UInt16;
    public let f1 : UInt8;
    public let f2 : UInt32;
    public let f3 : Int64;
    public let f4 : F10_S4_S0;
    public let f5 : Int64;
    public let f6 : UInt64;
    public let f7 : UInt32;
}

public func swiftFunc10(a0: Int, a1: F10_S0, a2: Int16, a3: F10_S1, a4: F10_S2, a5: UInt64, a6: F10_S3, a7: F10_S4) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1.f0);
    hasher.combine(a1.f1);
    hasher.combine(a1.f2);
    hasher.combine(a1.f3);
    hasher.combine(a1.f4);
    hasher.combine(a1.f5);
    hasher.combine(a2);
    hasher.combine(a3.f0);
    hasher.combine(a3.f1);
    hasher.combine(a3.f2);
    hasher.combine(a3.f3);
    hasher.combine(a4.f0);
    hasher.combine(a4.f1);
    hasher.combine(a5);
    hasher.combine(a6.f0);
    hasher.combine(a7.f0);
    hasher.combine(a7.f1);
    hasher.combine(a7.f2);
    hasher.combine(a7.f3);
    hasher.combine(a7.f4.f0);
    hasher.combine(a7.f4.f1);
    hasher.combine(a7.f4.f2);
    hasher.combine(a7.f5);
    hasher.combine(a7.f6);
    hasher.combine(a7.f7);
    return hasher.finalize()
}

public func swiftFunc11(a0: Int16, a1: Double, a2: Double, a3: UInt8, a4: Int32, a5: Int8) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4);
    hasher.combine(a5);
    return hasher.finalize()
}

@frozen
public struct F12_S0_S0
{
    public let f0 : Int64;
    public let f1 : Float;
    public let f2 : Int16;
    public let f3 : UInt;
}

@frozen
public struct F12_S0
{
    public let f0 : F12_S0_S0;
    public let f1 : UInt64;
}

@frozen
public struct F12_S1
{
    public let f0 : UInt8;
}

@frozen
public struct F12_S2
{
    public let f0 : UInt8;
    public let f1 : Int64;
    public let f2 : Int16;
    public let f3 : UInt64;
    public let f4 : UInt8;
    public let f5 : Int;
}

public func swiftFunc12(a0: F12_S0, a1: F12_S1, a2: F12_S2) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0.f0);
    hasher.combine(a0.f0.f1);
    hasher.combine(a0.f0.f2);
    hasher.combine(a0.f0.f3);
    hasher.combine(a0.f1);
    hasher.combine(a1.f0);
    hasher.combine(a2.f0);
    hasher.combine(a2.f1);
    hasher.combine(a2.f2);
    hasher.combine(a2.f3);
    hasher.combine(a2.f4);
    hasher.combine(a2.f5);
    return hasher.finalize()
}

@frozen
public struct F13_S0
{
    public let f0 : Int8;
    public let f1 : Double;
    public let f2 : Float;
    public let f3 : Int32;
    public let f4 : Int8;
    public let f5 : UInt16;
}

@frozen
public struct F13_S1_S0
{
    public let f0 : Int8;
    public let f1 : UInt8;
}

@frozen
public struct F13_S1_S1
{
    public let f0 : Int;
    public let f1 : Int16;
    public let f2 : Int64;
    public let f3 : Int16;
}

@frozen
public struct F13_S1_S2
{
    public let f0 : Int64;
}

@frozen
public struct F13_S1
{
    public let f0 : UInt32;
    public let f1 : F13_S1_S0;
    public let f2 : UInt16;
    public let f3 : Int32;
    public let f4 : Int16;
    public let f5 : F13_S1_S1;
    public let f6 : F13_S1_S2;
    public let f7 : UInt8;
}

@frozen
public struct F13_S2
{
    public let f0 : UInt8;
    public let f1 : Int;
    public let f2 : UInt32;
}

@frozen
public struct F13_S3_S0
{
    public let f0 : Float;
    public let f1 : UInt32;
    public let f2 : Int32;
    public let f3 : Int;
}

@frozen
public struct F13_S3
{
    public let f0 : UInt16;
    public let f1 : F13_S3_S0;
}

public func swiftFunc13(a0: F13_S0, a1: F13_S1, a2: F13_S2, a3: Int8, a4: F13_S3) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a0.f5);
    hasher.combine(a1.f0);
    hasher.combine(a1.f1.f0);
    hasher.combine(a1.f1.f1);
    hasher.combine(a1.f2);
    hasher.combine(a1.f3);
    hasher.combine(a1.f4);
    hasher.combine(a1.f5.f0);
    hasher.combine(a1.f5.f1);
    hasher.combine(a1.f5.f2);
    hasher.combine(a1.f5.f3);
    hasher.combine(a1.f6.f0);
    hasher.combine(a1.f7);
    hasher.combine(a2.f0);
    hasher.combine(a2.f1);
    hasher.combine(a2.f2);
    hasher.combine(a3);
    hasher.combine(a4.f0);
    hasher.combine(a4.f1.f0);
    hasher.combine(a4.f1.f1);
    hasher.combine(a4.f1.f2);
    hasher.combine(a4.f1.f3);
    return hasher.finalize()
}

@frozen
public struct F14_S0_S0
{
    public let f0 : UInt64;
}

@frozen
public struct F14_S0
{
    public let f0 : F14_S0_S0;
    public let f1 : Float;
    public let f2 : Int32;
    public let f3 : Int8;
    public let f4 : UInt16;
    public let f5 : Int;
    public let f6 : UInt32;
}

@frozen
public struct F14_S1
{
    public let f0 : Float;
    public let f1 : UInt8;
    public let f2 : UInt32;
    public let f3 : Int16;
}

@frozen
public struct F14_S2_S0_S0
{
    public let f0 : Int16;
    public let f1 : Int8;
    public let f2 : UInt8;
    public let f3 : UInt8;
}

@frozen
public struct F14_S2_S0
{
    public let f0 : F14_S2_S0_S0;
    public let f1 : Int64;
    public let f2 : Int8;
}

@frozen
public struct F14_S2
{
    public let f0 : Int32;
    public let f1 : F14_S2_S0;
    public let f2 : Int16;
    public let f3 : UInt16;
}

public func swiftFunc14(a0: F14_S0, a1: Double, a2: Int16, a3: Int8, a4: F14_S1, a5: F14_S2, a6: Int64) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a0.f5);
    hasher.combine(a0.f6);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3);
    hasher.combine(a4.f0);
    hasher.combine(a4.f1);
    hasher.combine(a4.f2);
    hasher.combine(a4.f3);
    hasher.combine(a5.f0);
    hasher.combine(a5.f1.f0.f0);
    hasher.combine(a5.f1.f0.f1);
    hasher.combine(a5.f1.f0.f2);
    hasher.combine(a5.f1.f0.f3);
    hasher.combine(a5.f1.f1);
    hasher.combine(a5.f1.f2);
    hasher.combine(a5.f2);
    hasher.combine(a5.f3);
    hasher.combine(a6);
    return hasher.finalize()
}

@frozen
public struct F15_S0
{
    public let f0 : Float;
    public let f1 : Int8;
    public let f2 : Double;
    public let f3 : Int32;
    public let f4 : Double;
    public let f5 : Int64;
    public let f6 : Int32;
    public let f7 : Int16;
}

public func swiftFunc15(a0: F15_S0) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a0.f2);
    hasher.combine(a0.f3);
    hasher.combine(a0.f4);
    hasher.combine(a0.f5);
    hasher.combine(a0.f6);
    hasher.combine(a0.f7);
    return hasher.finalize()
}

@frozen
public struct F16_S0
{
    public let f0 : Int32;
}

@frozen
public struct F16_S1
{
    public let f0 : UInt32;
}

@frozen
public struct F16_S2
{
    public let f0 : Int8;
    public let f1 : UInt8;
    public let f2 : Int64;
    public let f3 : Int;
    public let f4 : UInt32;
    public let f5 : Int64;
    public let f6 : Int64;
}

@frozen
public struct F16_S3
{
    public let f0 : Double;
    public let f1 : Double;
    public let f2 : Double;
    public let f3 : Double;
}

@frozen
public struct F16_S4_S0_S0
{
    public let f0 : UInt16;
    public let f1 : Int16;
    public let f2 : UInt;
    public let f3 : Int16;
}

@frozen
public struct F16_S4_S0
{
    public let f0 : Int64;
    public let f1 : Int8;
    public let f2 : UInt64;
    public let f3 : F16_S4_S0_S0;
}

@frozen
public struct F16_S4_S1
{
    public let f0 : Int16;
    public let f1 : UInt;
    public let f2 : Int;
}

@frozen
public struct F16_S4
{
    public let f0 : Float;
    public let f1 : F16_S4_S0;
    public let f2 : UInt16;
    public let f3 : Int16;
    public let f4 : F16_S4_S1;
    public let f5 : Double;
    public let f6 : UInt8;
}

public func swiftFunc16(a0: F16_S0, a1: UInt, a2: UInt64, a3: F16_S1, a4: F16_S2, a5: F16_S3, a6: Int32, a7: F16_S4) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3.f0);
    hasher.combine(a4.f0);
    hasher.combine(a4.f1);
    hasher.combine(a4.f2);
    hasher.combine(a4.f3);
    hasher.combine(a4.f4);
    hasher.combine(a4.f5);
    hasher.combine(a4.f6);
    hasher.combine(a5.f0);
    hasher.combine(a5.f1);
    hasher.combine(a5.f2);
    hasher.combine(a5.f3);
    hasher.combine(a6);
    hasher.combine(a7.f0);
    hasher.combine(a7.f1.f0);
    hasher.combine(a7.f1.f1);
    hasher.combine(a7.f1.f2);
    hasher.combine(a7.f1.f3.f0);
    hasher.combine(a7.f1.f3.f1);
    hasher.combine(a7.f1.f3.f2);
    hasher.combine(a7.f1.f3.f3);
    hasher.combine(a7.f2);
    hasher.combine(a7.f3);
    hasher.combine(a7.f4.f0);
    hasher.combine(a7.f4.f1);
    hasher.combine(a7.f4.f2);
    hasher.combine(a7.f5);
    hasher.combine(a7.f6);
    return hasher.finalize()
}

@frozen
public struct F17_S0
{
    public var elements: (Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16, Int16)
}

@frozen
public struct F17_S1
{
    public let f0 : Int8;
    public let f1 : Double;
    public let f2 : UInt;
    public let f3 : UInt8;
    public let f4 : Int64;
    public let f5 : Int8;
}

@frozen
public struct F17_S2_S0
{
    public let f0 : Int16;
    public let f1 : Int32;
    public let f2 : Int32;
    public let f3 : UInt32;
}

@frozen
public struct F17_S2
{
    public let f0 : F17_S2_S0;
}

@frozen
public struct F17_S3_S0
{
    public let f0 : UInt64;
}

@frozen
public struct F17_S3
{
    public let f0 : Double;
    public let f1 : UInt8;
    public let f2 : Int64;
    public let f3 : F17_S3_S0;
}

public func swiftFunc17(a0: Int8, a1: F17_S0, a2: F17_S1, a3: UInt8, a4: F17_S2, a5: F17_S3, a6: Int64) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1.elements.0);
    hasher.combine(a1.elements.1);
    hasher.combine(a1.elements.2);
    hasher.combine(a1.elements.3);
    hasher.combine(a1.elements.4);
    hasher.combine(a1.elements.5);
    hasher.combine(a1.elements.6);
    hasher.combine(a1.elements.7);
    hasher.combine(a1.elements.8);
    hasher.combine(a1.elements.9);
    hasher.combine(a1.elements.10);
    hasher.combine(a1.elements.11);
    hasher.combine(a1.elements.12);
    hasher.combine(a1.elements.13);
    hasher.combine(a1.elements.14);
    hasher.combine(a1.elements.15);
    hasher.combine(a2.f0);
    hasher.combine(a2.f1);
    hasher.combine(a2.f2);
    hasher.combine(a2.f3);
    hasher.combine(a2.f4);
    hasher.combine(a2.f5);
    hasher.combine(a3);
    hasher.combine(a4.f0.f0);
    hasher.combine(a4.f0.f1);
    hasher.combine(a4.f0.f2);
    hasher.combine(a4.f0.f3);
    hasher.combine(a5.f0);
    hasher.combine(a5.f1);
    hasher.combine(a5.f2);
    hasher.combine(a5.f3.f0);
    hasher.combine(a6);
    return hasher.finalize()
}

public func swiftFunc18(a0: Float, a1: UInt16) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0);
    hasher.combine(a1);
    return hasher.finalize()
}

@frozen
public struct F19_S0
{
    public let f0 : Float;
    public let f1 : Float;
}

@frozen
public struct F19_S1
{
    public let f0 : UInt32;
    public let f1 : Int8;
    public let f2 : UInt8;
    public let f3 : UInt8;
}

@frozen
public struct F19_S2
{
    public let f0 : Double;
    public let f1 : Int8;
    public let f2 : Float;
    public let f3 : Int16;
    public let f4 : Int16;
}

public func swiftFunc19(a0: F19_S0, a1: UInt64, a2: Double, a3: F19_S1, a4: UInt8, a5: UInt8, a6: F19_S2) -> Int {
    var hasher = HasherFNV1a()
    hasher.combine(a0.f0);
    hasher.combine(a0.f1);
    hasher.combine(a1);
    hasher.combine(a2);
    hasher.combine(a3.f0);
    hasher.combine(a3.f1);
    hasher.combine(a3.f2);
    hasher.combine(a3.f3);
    hasher.combine(a4);
    hasher.combine(a5);
    hasher.combine(a6.f0);
    hasher.combine(a6.f1);
    hasher.combine(a6.f2);
    hasher.combine(a6.f3);
    hasher.combine(a6.f4);
    return hasher.finalize()
}
