// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SwiftStressGenerator
{
    /// <summary>StringBuilder wrapper that always uses '\n' so output is byte-identical everywhere.</summary>
    internal sealed class CodeWriter
    {
        private readonly StringBuilder _sb = new();

        public void Line(string text = "")
        {
            _sb.Append(text);
            _sb.Append('\n');
        }

        public override string ToString() => _sb.ToString();
    }

    internal static class SwiftEmitter
    {
        public static string Emit(SuiteModel model)
        {
            var w = new CodeWriter();
            EmitHeader(w, model);

            if (model.Kind is SuiteKind.Args or SuiteKind.Calli)
                EmitHasher(w);

            if (model.Kind == SuiteKind.Invalid)
            {
                w.Line();
                w.Line("public func simpleFunc() { }");
                return w.ToString();
            }

            foreach (FunctionModel fn in model.Functions)
            {
                foreach (StructDecl decl in fn.StructDecls)
                    EmitStruct(w, decl);

                switch (fn.Kind)
                {
                    case FunctionKind.Args:
                        EmitArgsFunction(w, fn);
                        break;
                    case FunctionKind.Returns:
                        EmitReturnsFunction(w, fn);
                        break;
                    case FunctionKind.CallbackNormal:
                    case FunctionKind.CallbackSelfEnregistered:
                    case FunctionKind.CallbackSelfByRef:
                        EmitCallbackFunction(w, fn);
                        break;
                    default:
                        throw new InvalidOperationException();
                }
            }

            return w.ToString();
        }

        private static void EmitHeader(CodeWriter w, SuiteModel model)
        {
            w.Line("// Licensed to the .NET Foundation under one or more agreements.");
            w.Line("// The .NET Foundation licenses this file to you under the MIT license.");
            w.Line("//");
            w.Line("// Generated by src/tests/Interop/Swift/StressGenerator. Do not edit manually.");
            w.Line("// Regenerate with:");
            w.Line($"//   ./dotnet.sh run --project src/tests/Interop/Swift/StressGenerator -- {model.CommandLine}");
            w.Line();
            w.Line("import Foundation");
        }

        private static void EmitHasher(CodeWriter w)
        {
            w.Line();
            w.Line("struct HasherFNV1a {");
            w.Line();
            w.Line("    private var hash: UInt = 14_695_981_039_346_656_037");
            w.Line("    private let prime: UInt = 1_099_511_628_211");
            w.Line();
            w.Line("    mutating func combine<T>(_ val: T) {");
            w.Line("        for byte in withUnsafeBytes(of: val, Array.init) {");
            w.Line("            hash ^= UInt(byte)");
            w.Line("            hash = hash &* prime");
            w.Line("        }");
            w.Line("    }");
            w.Line();
            w.Line("    func finalize() -> Int {");
            w.Line("        Int(truncatingIfNeeded: hash)");
            w.Line("    }");
            w.Line("}");
        }

        private static void EmitStruct(CodeWriter w, StructDecl decl)
        {
            w.Line();
            w.Line("@frozen");
            w.Line($"public struct {decl.Name}");
            w.Line("{");
            if (decl.IsInlineArray)
            {
                string elems = string.Join(", ", Enumerable.Repeat(Primitives.SwiftName(decl.ElementKind), decl.ElementCount));
                w.Line($"    public var elements: ({elems})");
            }
            else
            {
                foreach ((string fieldName, TypeRef type) in decl.Fields)
                    w.Line($"    public let {fieldName} : {type.SwiftName};");
            }
            w.Line("}");
        }

        private static void EmitArgsFunction(CodeWriter w, FunctionModel fn)
        {
            string paramList = string.Join(", ", fn.Params.Select(p => $"{p.Name}: {p.Type.SwiftName}"));
            w.Line();
            w.Line($"public func {fn.SwiftFuncName}({paramList}) -> Int {{");
            w.Line("    var hasher = HasherFNV1a()");
            foreach (ParamModel p in fn.Params)
            {
                foreach (LeafSlot leaf in p.Type.Leaves(0, p.Name, p.Name))
                    w.Line($"    hasher.combine({leaf.SwiftPath});");
            }
            w.Line("    return hasher.finalize()");
            w.Line("}");
        }

        private static void EmitReturnsFunction(CodeWriter w, FunctionModel fn)
        {
            var retType = (StructDecl)fn.ReturnTree!.Type;
            w.Line();
            w.Line($"public func {fn.SwiftFuncName}() -> {retType.Name} {{");
            w.Line($"    return {BuildConstructor(fn.ReturnTree)}");
            w.Line("}");
        }

        private static void EmitCallbackFunction(CodeWriter w, FunctionModel fn)
        {
            var closureParamTypes = fn.Params.Select(p => p.Type.SwiftName).ToList();
            var closureArgs = fn.Params.Select(p => BuildConstructor(p.Values)).ToList();
            string returnType;

            if (fn.Kind == FunctionKind.CallbackNormal)
            {
                returnType = Primitives.SwiftName(fn.CallbackReturnKind);
            }
            else
            {
                returnType = "Int64";
                if (fn.Kind == FunctionKind.CallbackSelfEnregistered)
                {
                    // The self struct is passed as a trailing ordinary argument,
                    // physically identical to a directly-lowered self value.
                    closureParamTypes.Add(fn.SelfStruct!.Name);
                    closureArgs.Add(BuildConstructor(fn.SelfValues!));
                }
                // For the by-reference case the managed caller supplies the self
                // value through the closure context, so the Swift closure type
                // carries no extra parameter.
            }

            w.Line();
            w.Line($"public func {fn.SwiftFuncName}(f: ({string.Join(", ", closureParamTypes)}) -> {returnType}) -> {returnType} {{");
            w.Line($"    return f({string.Join(", ", closureArgs)})");
            w.Line("}");
        }

        private static string BuildConstructor(ValueTree tree)
        {
            if (tree.Primitive != null)
                return tree.Primitive.SwiftLiteral;

            var decl = (StructDecl)tree.Type;
            if (decl.IsInlineArray)
                return $"{decl.Name}(elements: ({string.Join(", ", tree.Elements.Select(v => v.SwiftLiteral))}))";

            var parts = new List<string>();
            for (int i = 0; i < decl.Fields.Count; i++)
                parts.Add($"{decl.Fields[i].FieldName}: {BuildConstructor(tree.Fields[i])}");
            return $"{decl.Name}({string.Join(", ", parts)})";
        }
    }

    internal static class CSharpEmitter
    {
        private static readonly CultureInfo s_inv = CultureInfo.InvariantCulture;

        public static string Emit(SuiteModel model)
        {
            var w = new CodeWriter();
            EmitHeader(w, model);
            EmitUsings(w, model);

            w.Line("[PlatformSpecific(TestPlatforms.AnyApple)]");
            if (model.Kind is SuiteKind.Returns or SuiteKind.Callbacks)
                w.Line("[ActiveIssue(\"https://github.com/dotnet/runtime/issues/121983\", typeof(PlatformDetection), nameof(PlatformDetection.IsMonoMiniJIT), nameof(PlatformDetection.IsX64Process))]");
            w.Line($"public unsafe class {model.Name}");
            w.Line("{");
            w.Line($"    private const string SwiftLib = \"lib{model.Name}.dylib\";");

            switch (model.Kind)
            {
                case SuiteKind.Args:
                    EmitArgsBody(w, model, calli: false);
                    break;
                case SuiteKind.Calli:
                    EmitArgsBody(w, model, calli: true);
                    break;
                case SuiteKind.Returns:
                    EmitReturnsBody(w, model);
                    break;
                case SuiteKind.Callbacks:
                    EmitCallbacksBody(w, model);
                    break;
                case SuiteKind.Invalid:
                    EmitInvalidBody(w, model);
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            w.Line("}");
            return w.ToString();
        }

        private static void EmitHeader(CodeWriter w, SuiteModel model)
        {
            w.Line("// Licensed to the .NET Foundation under one or more agreements.");
            w.Line("// The .NET Foundation licenses this file to you under the MIT license.");
            w.Line("//");
            w.Line("// Generated by src/tests/Interop/Swift/StressGenerator. Do not edit manually.");
            w.Line("// Regenerate with:");
            w.Line($"//   ./dotnet.sh run --project src/tests/Interop/Swift/StressGenerator -- {model.CommandLine}");
            w.Line();
        }

        private static void EmitUsings(CodeWriter w, SuiteModel model)
        {
            w.Line("using System;");
            if (model.Kind == SuiteKind.Invalid)
                w.Line("using System.Reflection;");
            w.Line("using System.Runtime.CompilerServices;");
            if (model.Kind == SuiteKind.Callbacks)
                w.Line("using System.Runtime.ExceptionServices;");
            w.Line("using System.Runtime.InteropServices;");
            w.Line("using System.Runtime.InteropServices.Swift;");
            w.Line("using Xunit;");
            w.Line("using TestLibrary;");
            w.Line();
        }

        private static void EmitStruct(CodeWriter w, StructDecl decl)
        {
            w.Line();
            if (decl.IsInlineArray)
            {
                w.Line($"    [InlineArray({decl.ElementCount.ToString(s_inv)})]");
                w.Line($"    struct {decl.Name}");
                w.Line("    {");
                w.Line($"        private {Primitives.CSharpName(decl.ElementKind)} _element0;");
                w.Line("    }");
                return;
            }

            w.Line($"    [StructLayout(LayoutKind.Sequential, Size = {decl.Size.ToString(s_inv)})]");
            w.Line($"    struct {decl.Name}");
            w.Line("    {");
            for (int i = 0; i < decl.Fields.Count; i++)
                w.Line($"        public {decl.Fields[i].Type.CSharpName} {StructDecl.CSharpFieldName(i)};");
            w.Line();
            string ctorParams = string.Join(", ", decl.Fields.Select((f, i) => $"{f.Type.CSharpName} f{i.ToString(s_inv)}"));
            w.Line($"        public {decl.Name}({ctorParams})");
            w.Line("        {");
            for (int i = 0; i < decl.Fields.Count; i++)
                w.Line($"            {StructDecl.CSharpFieldName(i)} = f{i.ToString(s_inv)};");
            w.Line("        }");
            w.Line("    }");
        }

        // Builds the C# argument expression for a value tree; inline-array
        // arguments are prepared as locals via EmitInlineArraySetup instead.
        private static string BuildCtor(ValueTree tree)
        {
            if (tree.Primitive != null)
                return tree.Primitive.CSharpLiteral;

            var decl = (StructDecl)tree.Type;
            if (decl.IsInlineArray)
                throw new InvalidOperationException("inline arrays must be prepared as locals");

            var parts = new List<string>();
            for (int i = 0; i < decl.Fields.Count; i++)
                parts.Add(BuildCtor(tree.Fields[i]));
            return $"new {decl.Name}({string.Join(", ", parts)})";
        }

        private static void EmitInlineArraySetup(CodeWriter w, string local, ValueTree tree)
        {
            var decl = (StructDecl)tree.Type;
            string elemType = Primitives.CSharpName(decl.ElementKind);
            w.Line($"        {decl.Name} {local} = default;");
            w.Line($"        {elemType}* ptr_{local} = ({elemType}*)&{local};");
            for (int i = 0; i < tree.Elements.Count; i++)
                w.Line($"        ptr_{local}[{i.ToString(s_inv)}] = {tree.Elements[i].CSharpTypedLiteral};");
        }

        private static bool IsInlineArray(TypeRef type) => type is StructDecl { IsInlineArray: true };

        private static string HashLiteral(long hash) =>
            hash == long.MinValue ? "unchecked((long)9223372036854775808UL)" : hash.ToString(s_inv);

        private static void EmitArgsBody(CodeWriter w, SuiteModel model, bool calli)
        {
            foreach (FunctionModel fn in model.Functions)
            {
                string index = fn.Index.ToString(s_inv);
                foreach (StructDecl decl in fn.StructDecls)
                    EmitStruct(w, decl);

                string csParams = string.Join(", ", fn.Params.Select(p => $"{p.Type.CSharpName} {p.Name}"));
                string fnPtrType = $"delegate* unmanaged[Swift]<{string.Join(", ", fn.Params.Select(p => p.Type.CSharpName).Append("nint"))}>";

                if (!calli)
                {
                    w.Line();
                    w.Line("    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]");
                    w.Line($"    [DllImport(SwiftLib, EntryPoint = \"{fn.MangledName}\")]");
                    w.Line($"    private static extern nint SwiftFunc{index}({csParams});");
                }

                w.Line();
                w.Line("    [Fact]");
                w.Line($"    public static void Test{(calli ? "DirectCalli" : "Swift")}Func{index}()");
                w.Line("    {");
                w.Line($"        Console.Write(\"Running SwiftFunc{index}{(calli ? " (calli)" : "")}: \");");

                var argExprs = new List<string>();
                foreach (ParamModel p in fn.Params)
                {
                    if (IsInlineArray(p.Type))
                    {
                        EmitInlineArraySetup(w, p.Name, p.Values);
                        argExprs.Add(p.Name);
                    }
                    else
                    {
                        argExprs.Add(BuildCtor(p.Values));
                    }
                }

                if (calli)
                {
                    w.Line("        IntPtr lib = NativeLibrary.Load(SwiftLib, System.Reflection.Assembly.GetExecutingAssembly(), null);");
                    w.Line($"        var fn = ({fnPtrType})NativeLibrary.GetExport(lib, \"{fn.MangledName}\");");
                    w.Line($"        long result = fn({string.Join(", ", argExprs)});");
                }
                else
                {
                    w.Line($"        long result = SwiftFunc{index}({string.Join(", ", argExprs)});");
                }

                w.Line($"        Assert.Equal({HashLiteral(fn.ExpectedHash)}, result);");
                w.Line("        Console.WriteLine(\"OK\");");
                w.Line("    }");
            }
        }

        private static void EmitReturnsBody(CodeWriter w, SuiteModel model)
        {
            foreach (FunctionModel fn in model.Functions)
            {
                string index = fn.Index.ToString(s_inv);
                foreach (StructDecl decl in fn.StructDecls)
                    EmitStruct(w, decl);

                var retType = (StructDecl)fn.ReturnTree!.Type;
                w.Line();
                w.Line("    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]");
                w.Line($"    [DllImport(SwiftLib, EntryPoint = \"{fn.MangledName}\")]");
                w.Line($"    private static extern {retType.Name} SwiftRetFunc{index}();");

                w.Line();
                w.Line("    [Fact]");
                w.Line($"    public static void TestSwiftRetFunc{index}()");
                w.Line("    {");
                w.Line($"        Console.Write(\"Running SwiftRetFunc{index}: \");");
                w.Line($"        {retType.Name} val = SwiftRetFunc{index}();");

                if (retType.IsInlineArray)
                {
                    string elemType = Primitives.CSharpName(retType.ElementKind);
                    w.Line($"        {elemType}* ptr_val = ({elemType}*)&val;");
                    for (int i = 0; i < fn.ReturnTree.Elements.Count; i++)
                        w.Line($"        Assert.Equal({fn.ReturnTree.Elements[i].CSharpTypedLiteral}, ptr_val[{i.ToString(s_inv)}]);");
                }
                else
                {
                    var leaves = retType.Leaves(0, "val", "val").ToList();
                    var values = fn.ReturnTree.FlattenValues().ToList();
                    for (int i = 0; i < leaves.Count; i++)
                        w.Line($"        Assert.Equal({values[i].CSharpTypedLiteral}, {leaves[i].CSharpPath});");
                }

                w.Line("        Console.WriteLine(\"OK\");");
                w.Line("    }");
            }
        }

        private static void EmitCallbacksBody(CodeWriter w, SuiteModel model)
        {
            if (model.Functions.Any(f => f.Kind is FunctionKind.CallbackSelfEnregistered or FunctionKind.CallbackSelfByRef))
                EmitCSharpHasher(w);

            foreach (FunctionModel fn in model.Functions)
            {
                if (fn.Kind == FunctionKind.CallbackNormal)
                    EmitNormalCallback(w, fn);
                else
                    EmitSelfCallback(w, fn);
            }
        }

        private static void EmitCSharpHasher(CodeWriter w)
        {
            w.Line();
            w.Line("    // FNV-1a over the in-memory bytes of each combined value; matches the");
            w.Line("    // HasherFNV1a in the Swift sources and in the generator.");
            w.Line("    struct HasherFNV1a");
            w.Line("    {");
            w.Line("        private ulong _hash;");
            w.Line();
            w.Line("        public static HasherFNV1a Create()");
            w.Line("        {");
            w.Line("            return new HasherFNV1a { _hash = 14695981039346656037 };");
            w.Line("        }");
            w.Line();
            w.Line("        public void Combine<T>(T val) where T : unmanaged");
            w.Line("        {");
            w.Line("            byte* p = (byte*)&val;");
            w.Line("            for (int i = 0; i < sizeof(T); i++)");
            w.Line("            {");
            w.Line("                _hash ^= p[i];");
            w.Line("                _hash = unchecked(_hash * 1099511628211);");
            w.Line("            }");
            w.Line("        }");
            w.Line();
            w.Line("        public long Finish()");
            w.Line("        {");
            w.Line("            return unchecked((long)_hash);");
            w.Line("        }");
            w.Line("    }");
        }

        private static void EmitNormalCallback(CodeWriter w, FunctionModel fn)
        {
            string index = fn.Index.ToString(s_inv);
            foreach (StructDecl decl in fn.StructDecls)
                EmitStruct(w, decl);

            string retType = Primitives.CSharpName(fn.CallbackReturnKind);
            string fnPtrType = $"delegate* unmanaged[Swift]<{string.Join(", ", fn.Params.Select(p => p.Type.CSharpName).Append("SwiftSelf").Append(retType))}>";

            w.Line();
            w.Line("    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]");
            w.Line($"    [DllImport(SwiftLib, EntryPoint = \"{fn.MangledName}\")]");
            w.Line($"    private static extern {retType} SwiftCallbackFunc{index}({fnPtrType} func, void* funcContext);");

            w.Line();
            w.Line("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvSwift)])]");
            string cbParams = string.Join(", ", fn.Params.Select(p => $"{p.Type.CSharpName} {p.Name}").Append("SwiftSelf self"));
            w.Line($"    private static {retType} SwiftCallbackFunc{index}Callback({cbParams})");
            w.Line("    {");
            w.Line("        try");
            w.Line("        {");
            foreach (ParamModel p in fn.Params)
            {
                var leaves = p.Type.Leaves(0, p.Name, p.Name).ToList();
                var values = p.Values.FlattenValues().ToList();
                for (int i = 0; i < leaves.Count; i++)
                    w.Line($"            Assert.Equal({values[i].CSharpTypedLiteral}, {leaves[i].CSharpPath});");
            }
            w.Line("        }");
            w.Line("        catch (Exception ex)");
            w.Line("        {");
            w.Line("            *(ExceptionDispatchInfo*)self.Value = ExceptionDispatchInfo.Capture(ex);");
            w.Line("        }");
            w.Line();
            w.Line($"        return {fn.CallbackReturnValue!.CSharpLiteral};");
            w.Line("    }");

            w.Line();
            w.Line("    [Fact]");
            w.Line($"    public static void TestSwiftCallbackFunc{index}()");
            w.Line("    {");
            w.Line($"        Console.Write(\"Running SwiftCallbackFunc{index}: \");");
            w.Line("        ExceptionDispatchInfo ex = null;");
            w.Line($"        {retType} val = SwiftCallbackFunc{index}(&SwiftCallbackFunc{index}Callback, &ex);");
            w.Line("        if (ex != null)");
            w.Line("            ex.Throw();");
            w.Line();
            w.Line($"        Assert.Equal({fn.CallbackReturnValue!.CSharpTypedLiteral}, val);");
            w.Line("        Console.WriteLine(\"OK\");");
            w.Line("    }");
        }

        private static void EmitSelfCallback(CodeWriter w, FunctionModel fn)
        {
            string index = fn.Index.ToString(s_inv);
            bool enregistered = fn.Kind == FunctionKind.CallbackSelfEnregistered;
            foreach (StructDecl decl in fn.StructDecls)
                EmitStruct(w, decl);

            string selfType = $"SwiftSelf<{fn.SelfStruct!.Name}>";
            string fnPtrType = $"delegate* unmanaged[Swift]<{string.Join(", ", fn.Params.Select(p => p.Type.CSharpName).Append(selfType).Append("long"))}>";

            w.Line();
            if (enregistered)
                w.Line($"    // The self value lowers to at most four elements, so Swift passes it directly (enregistered).");
            else
                w.Line($"    // The self value lowers to more than four elements, so Swift passes it by reference in the context register.");
            w.Line("    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]");
            w.Line($"    [DllImport(SwiftLib, EntryPoint = \"{fn.MangledName}\")]");
            w.Line($"    private static extern long SwiftCallbackFunc{index}({fnPtrType} func, void* funcContext);");

            w.Line();
            w.Line("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvSwift)])]");
            string cbParams = string.Join(", ", fn.Params.Select(p => $"{p.Type.CSharpName} {p.Name}").Append($"{selfType} self"));
            w.Line($"    private static long SwiftCallbackFunc{index}Callback({cbParams})");
            w.Line("    {");
            w.Line("        HasherFNV1a hasher = HasherFNV1a.Create();");
            foreach (ParamModel p in fn.Params)
                w.Line($"        hasher.Combine({p.Name});");
            w.Line($"        {fn.SelfStruct.Name} s = self.Value;");
            foreach (LeafSlot leaf in fn.SelfStruct.Leaves(0, "s", "s"))
                w.Line($"        hasher.Combine({leaf.CSharpPath});");
            w.Line("        return hasher.Finish();");
            w.Line("    }");

            w.Line();
            w.Line("    [Fact]");
            w.Line($"    public static void TestSwiftCallbackFunc{index}()");
            w.Line("    {");
            w.Line($"        Console.Write(\"Running SwiftCallbackFunc{index}: \");");
            if (enregistered)
            {
                w.Line($"        long result = SwiftCallbackFunc{index}(&SwiftCallbackFunc{index}Callback, null);");
            }
            else
            {
                w.Line($"        {fn.SelfStruct.Name} self = {BuildCtor(fn.SelfValues!)};");
                w.Line($"        long result = SwiftCallbackFunc{index}(&SwiftCallbackFunc{index}Callback, &self);");
            }
            w.Line($"        Assert.Equal({HashLiteral(fn.ExpectedHash)}, result);");
            w.Line("        Console.WriteLine(\"OK\");");
            w.Line("    }");
        }

        private static void EmitInvalidBody(CodeWriter w, SuiteModel model)
        {
            bool needsStruct = model.Functions.Any(f => f.InvalidKind is InvalidKind.SelfTNotLast or InvalidKind.DupSelfAndSelfT);
            bool needsReverse = model.Functions.Any(f => f.HasReverseVariant);

            if (needsStruct)
            {
                w.Line();
                w.Line("    public struct S0");
                w.Line("    {");
                w.Line("        public long F0;");
                w.Line("    }");
            }

            foreach (FunctionModel fn in model.Functions)
                EmitInvalidFunction(w, model, fn);

            if (needsReverse)
            {
                w.Line();
                w.Line("    private static void PrepareReverseMethod(string name)");
                w.Line("    {");
                w.Line($"        MethodInfo method = typeof({model.Name}).GetMethod(name, BindingFlags.NonPublic | BindingFlags.Static)!;");
                w.Line("        RuntimeHelpers.PrepareMethod(method.MethodHandle);");
                w.Line("    }");
            }
        }

        private static void EmitInvalidFunction(CodeWriter w, SuiteModel model, FunctionModel fn)
        {
            string index = fn.Index.ToString(s_inv);
            string fillers = string.Join(", ", fn.Params.Select(p => $"{p.Type.CSharpName} {p.Name}"));
            string fillerArgs = string.Join(", ", fn.Params.Select(p => p.Values.Primitive!.CSharpLiteral));

            (string signature, string callArgs, string reverseSignature, string comment) = fn.InvalidKind switch
            {
                InvalidKind.DupSwiftSelf => (
                    Join("SwiftSelf self1", fillers, "SwiftSelf self2"),
                    Join("self", fillerArgs, "self"),
                    Join("SwiftSelf self1", fillers, "SwiftSelf self2"),
                    "multiple SwiftSelf arguments"),
                InvalidKind.DupSwiftError => (
                    Join("ref SwiftError error1", fillers, "ref SwiftError error2"),
                    Join("ref error", fillerArgs, "ref error"),
                    string.Empty,
                    "multiple SwiftError arguments"),
                InvalidKind.SwiftErrorByValue => (
                    Join("SwiftError error1", fillers, null),
                    Join("error", fillerArgs, null),
                    string.Empty,
                    "SwiftError not passed as a pointer"),
                InvalidKind.SelfTNotLast => (
                    Join("SwiftSelf<S0> self", fillers, "int x"),
                    Join("new SwiftSelf<S0>()", fillerArgs, "0"),
                    Join("SwiftSelf<S0> self", fillers, "int x"),
                    "SwiftSelf<T> not the last argument"),
                InvalidKind.DupSelfAndSelfT => (
                    Join("SwiftSelf self1", fillers, "SwiftSelf<S0> selfT"),
                    Join("self", fillerArgs, "new SwiftSelf<S0>()"),
                    Join("SwiftSelf self1", fillers, "SwiftSelf<S0> selfT"),
                    "both SwiftSelf and SwiftSelf<T> present"),
                _ => throw new ArgumentOutOfRangeException(),
            };

            w.Line();
            w.Line("    [UnmanagedCallConv(CallConvs = [typeof(CallConvSwift)])]");
            w.Line($"    [DllImport(SwiftLib, EntryPoint = \"{fn.MangledName}\")]");
            w.Line($"    private static extern void InvalidFunc{index}({signature});");

            w.Line();
            w.Line("    [Fact]");
            w.Line($"    public static void TestInvalidFunc{index}()");
            w.Line("    {");
            w.Line($"        // Invalid due to {comment}.");
            if (fn.InvalidKind is InvalidKind.DupSwiftSelf or InvalidKind.DupSelfAndSelfT)
                w.Line("        SwiftSelf self = new SwiftSelf();");
            if (fn.InvalidKind is InvalidKind.DupSwiftError or InvalidKind.SwiftErrorByValue)
                w.Line("        SwiftError error = new SwiftError();");
            w.Line($"        Assert.Throws<InvalidProgramException>(() => InvalidFunc{index}({callArgs}));");
            w.Line("    }");

            if (fn.HasReverseVariant)
            {
                w.Line();
                w.Line("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvSwift)])]");
                w.Line($"    private static void ReverseInvalidFunc{index}({reverseSignature}) {{ }}");

                w.Line();
                w.Line("    [Fact]");
                w.Line($"    public static void TestReverseInvalidFunc{index}()");
                w.Line("    {");
                w.Line("        // The CoreCLR interpreter validates reverse signatures when the native");
                w.Line("        // entry stub is created, which PrepareMethod does not exercise.");
                w.Line("        if (TestLibrary.Utilities.IsCoreClrInterpreter)");
                w.Line("            return;");
                w.Line();
                w.Line($"        // Invalid due to {comment}.");
                w.Line($"        Assert.Throws<InvalidProgramException>(() => PrepareReverseMethod(nameof(ReverseInvalidFunc{index})));");
                w.Line("    }");
            }
        }

        private static string Join(string first, string middle, string? last)
        {
            var parts = new List<string> { first };
            if (middle.Length > 0)
                parts.Add(middle);
            if (!string.IsNullOrEmpty(last))
                parts.Add(last);
            return string.Join(", ", parts);
        }
    }

    internal static class ProjectEmitter
    {
        public static string EmitCMakeLists(SuiteModel model)
        {
            string evolution = model.LibraryEvolution ? "-enable-library-evolution " : string.Empty;
            var w = new CodeWriter();
            w.Line("# Generated by src/tests/Interop/Swift/StressGenerator. Do not edit manually.");
            w.Line($"project({model.Name})");
            w.Line("include (\"${CLR_INTEROP_TEST_ROOT}/Interop.cmake\")");
            w.Line();
            w.Line($"set(SOURCE {model.Name})");
            w.Line();
            w.Line("if (NOT SWIFT_COMPILER_TARGET AND CLR_CMAKE_TARGET_APPLE)");
            w.Line("    set(SWIFT_PLATFORM \"macosx\")");
            w.Line("    set(SWIFT_PLATFORM_SUFFIX \"\")");
            w.Line("    if (NOT CMAKE_OSX_DEPLOYMENT_TARGET)");
            w.Line("        set(CMAKE_OSX_DEPLOYMENT_TARGET \"14.0\")");
            w.Line("    endif()");
            w.Line("    set(SWIFT_DEPLOYMENT_TARGET ${CMAKE_OSX_DEPLOYMENT_TARGET})");
            w.Line("    set(SWIFT_COMPILER_TARGET \"${CMAKE_OSX_ARCHITECTURES}-apple-${SWIFT_PLATFORM}${SWIFT_DEPLOYMENT_TARGET}${SWIFT_PLATFORM_SUFFIX}\")");
            w.Line("endif()");
            w.Line();
            w.Line("add_custom_target(${SOURCE} ALL");
            w.Line($"    COMMAND xcrun swiftc -target ${{SWIFT_COMPILER_TARGET}} {evolution}-module-name ${{SOURCE}} -emit-library ${{CMAKE_CURRENT_SOURCE_DIR}}/${{SOURCE}}.swift -o ${{CMAKE_CURRENT_BINARY_DIR}}/lib${{SOURCE}}.dylib");
            w.Line("    DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}.swift");
            w.Line("    COMMENT \"Generating ${SOURCE} library\"");
            w.Line(")");
            w.Line();
            w.Line("install(FILES ${CMAKE_CURRENT_BINARY_DIR}/lib${SOURCE}.dylib");
            w.Line("    DESTINATION bin");
            w.Line(")");
            return w.ToString();
        }

        public static string EmitCsproj()
        {
            var w = new CodeWriter();
            w.Line("<Project Sdk=\"Microsoft.NET.Sdk\">");
            w.Line("  <PropertyGroup>");
            w.Line("    <!-- Needed for CLRTestTargetUnsupported, CMakeProjectReference -->");
            w.Line("    <RequiresProcessIsolation>true</RequiresProcessIsolation>");
            w.Line("    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>");
            w.Line("  </PropertyGroup>");
            w.Line("  <ItemGroup>");
            w.Line("    <Compile Include=\"$(MSBuildProjectName).cs\" />");
            w.Line("  </ItemGroup>");
            w.Line("  <ItemGroup>");
            w.Line("    <ProjectReference Include=\"$(TestLibraryProjectPath)\" />");
            w.Line("    <CMakeProjectReference Include=\"CMakeLists.txt\" />");
            w.Line("  </ItemGroup>");
            w.Line("</Project>");
            return w.ToString();
        }
    }
}
