<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestPriority>1</CLRTestPriority>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CooperativeGC.cs" />
    <ProjectReference Include="CooperativeLoops.ilproj" />
  </ItemGroup>
</Project>
